# Generated by Django 4.1.3 on 2022-11-29 11:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='car_model',
            field=models.CharField(default=1990, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='car_year',
            field=models.IntegerField(default=account.models.current_year),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
